import type { Subject, PhaseInfo, CheatSheetItem, CheatSheetDifficulty } from './types';

// Color palette for subjects — calm blues and earthy accent colors
// Avoiding indigo/blue defaults; using a custom palette
const SUBJECT_COLORS = {
  math: 'text-emerald-600',
  discrete: 'text-teal-600',
  digital: 'text-amber-600',
  coa: 'text-orange-600',
  ds: 'text-cyan-600',
  algo: 'text-rose-600',
  toc: 'text-violet-600',
  compiler: 'text-fuchsia-600',
  os: 'text-red-600',
  dbms: 'text-lime-600',
  networks: 'text-sky-600',
  aptitude: 'text-stone-600',
};

export const SEED_SUBJECTS: Subject[] = [
  {
    id: 'eng-math',
    name: 'Engineering Mathematics',
    shortName: 'Eng Math',
    priority: 'P0',
    status: 'weak',
    weightage: '13-15',
    targetMarks: '11-13',
    resource: 'Made Easy Math workbook + B.S. Grewal',
    color: SUBJECT_COLORS.math,
    mustMasterTopics: [
      { id: 'em-1', name: 'Linear Algebra (matrices, eigenvalues, system of equations)', completed: false },
      { id: 'em-2', name: 'Calculus (limits, differentiation, integration, maxima-minima)', completed: false },
      { id: 'em-3', name: 'Probability (random variables, distributions, Bayes)', completed: false },
      { id: 'em-4', name: 'Statistics (mean, variance, standard distributions)', completed: false },
      { id: 'em-5', name: 'Numerical Methods (Newton-Raphson, integration)', completed: false },
    ],
  },
  {
    id: 'discrete',
    name: 'Discrete Mathematics',
    shortName: 'Discrete',
    priority: 'P0',
    status: 'weak',
    weightage: '6-8',
    targetMarks: '5-6',
    resource: 'Kenneth Rosen + Gate Smashers videos',
    color: SUBJECT_COLORS.discrete,
    mustMasterTopics: [
      { id: 'dm-1', name: 'Propositional & first-order logic', completed: false },
      { id: 'dm-2', name: 'Set theory, relations, functions', completed: false },
      { id: 'dm-3', name: 'Combinatorics (counting, generating functions)', completed: false },
      { id: 'dm-4', name: 'Graph theory (planar, Euler, coloring)', completed: false },
      { id: 'dm-5', name: 'Group theory (subgroups, homomorphism)', completed: false },
    ],
  },
  {
    id: 'digital-logic',
    name: 'Digital Logic',
    shortName: 'Digital Logic',
    priority: 'P2',
    status: 'moderate',
    weightage: '4-5',
    targetMarks: '4-5',
    resource: 'Morris Mano + Made Easy DL workbook',
    color: SUBJECT_COLORS.digital,
    mustMasterTopics: [
      { id: 'dl-1', name: 'Number systems & conversions (incl. fractional)', completed: false },
      { id: 'dl-2', name: 'Boolean algebra & K-map (3,4,5 variables)', completed: false },
      { id: 'dl-3', name: 'Combinational circuits (adder, MUX, decoder)', completed: false },
      { id: 'dl-4', name: 'Sequential circuits (flip-flops, counters)', completed: false },
      { id: 'dl-5', name: 'IEEE 754 floating-point representation', completed: false },
    ],
  },
  {
    id: 'coa',
    name: 'Computer Organisation & Architecture',
    shortName: 'COA',
    priority: 'P1',
    status: 'moderate',
    weightage: '6-8',
    targetMarks: '5-7',
    resource: 'Hamacher + Patterson & Hennessy',
    color: SUBJECT_COLORS.coa,
    mustMasterTopics: [
      { id: 'coa-1', name: 'Instruction pipelining (hazards, forwarding)', completed: false },
      { id: 'coa-2', name: 'Cache memory (direct, set-assoc, hit/miss calc)', completed: false },
      { id: 'coa-3', name: 'Addressing modes & CPI calculation', completed: false },
      { id: 'coa-4', name: 'Memory hierarchy & virtual memory', completed: false },
      { id: 'coa-5', name: 'I/O techniques (programmed, interrupt, DMA)', completed: false },
    ],
  },
  {
    id: 'ds',
    name: 'Programming & Data Structures',
    shortName: 'DS / C',
    priority: 'P1',
    status: 'moderate',
    weightage: '8-10',
    targetMarks: '7-9',
    resource: 'Tanenbaum + Made Easy C/DS workbook',
    color: SUBJECT_COLORS.ds,
    mustMasterTopics: [
      { id: 'ds-1', name: 'C pointers, arrays, structures, function pointers', completed: false },
      { id: 'ds-2', name: 'Linked lists (singly, doubly, circular)', completed: false },
      { id: 'ds-3', name: 'Stacks, queues, priority queues', completed: false },
      { id: 'ds-4', name: 'Trees (BST, AVL rotations, B-tree, heap)', completed: false },
      { id: 'ds-5', name: 'Graphs (BFS, DFS, topological sort) + hash tables', completed: false },
    ],
  },
  {
    id: 'algorithms',
    name: 'Algorithms',
    shortName: 'Algorithms',
    priority: 'P0',
    status: 'weak',
    weightage: '10-12',
    targetMarks: '8-10',
    resource: 'CLRS (selected) + Aditya Verma DP playlist',
    color: SUBJECT_COLORS.algo,
    mustMasterTopics: [
      { id: 'al-1', name: 'Asymptotic analysis & Master theorem', completed: false },
      { id: 'al-2', name: 'Divide & Conquer (merge sort, quick sort, recurrences)', completed: false },
      { id: 'al-3', name: 'Greedy (Huffman, Kruskal, Prim, Dijkstra)', completed: false },
      { id: 'al-4', name: 'Dynamic Programming (LCS, knapsack, edit distance)', completed: false },
      { id: 'al-5', name: 'Backtracking + P/NP completeness', completed: false },
    ],
  },
  {
    id: 'toc',
    name: 'Theory of Computation',
    shortName: 'TOC',
    priority: 'P0',
    status: 'weak',
    weightage: '6-8',
    targetMarks: '5-6',
    resource: 'Hopcroft + Ullman + NocsAlgo YouTube',
    color: SUBJECT_COLORS.toc,
    mustMasterTopics: [
      { id: 'tc-1', name: 'DFA/NFA construction & conversion', completed: false },
      { id: 'tc-2', name: 'DFA minimization (Myhill-Nerode)', completed: false },
      { id: 'tc-3', name: 'Regular expressions & Arden\'s lemma', completed: false },
      { id: 'tc-4', name: 'Pumping lemma for regular languages', completed: false },
      { id: 'tc-5', name: 'CFG, ambiguity, LL(1) parsing, PDA, Turing machines', completed: false },
    ],
  },
  {
    id: 'compiler',
    name: 'Compiler Design',
    shortName: 'Compiler',
    priority: 'P1',
    status: 'weak',
    weightage: '4-6',
    targetMarks: '4-5',
    resource: 'Dragon book (selected) + Made Easy workbook',
    color: SUBJECT_COLORS.compiler,
    mustMasterTopics: [
      { id: 'cp-1', name: 'Lexical analysis & regex to DFA', completed: false },
      { id: 'cp-2', name: 'Top-down parsing (LL(1), FIRST/FOLLOW)', completed: false },
      { id: 'cp-3', name: 'Bottom-up parsing (LR(0), SLR, LALR, CLR)', completed: false },
      { id: 'cp-4', name: 'Syntax-directed translation (S/L-attributed)', completed: false },
      { id: 'cp-5', name: 'Intermediate code & code optimization', completed: false },
    ],
  },
  {
    id: 'os',
    name: 'Operating System',
    shortName: 'OS',
    priority: 'P0',
    status: 'weak',
    weightage: '8-10',
    targetMarks: '7-9',
    resource: 'Silberschatz (Galvin) + Gate Smashers',
    color: SUBJECT_COLORS.os,
    mustMasterTopics: [
      { id: 'os-1', name: 'CPU scheduling (FCFS, SJF, RR, MLFQ)', completed: false },
      { id: 'os-2', name: 'Synchronisation (semaphores, classic problems)', completed: false },
      { id: 'os-3', name: 'Deadlocks (Banker\'s algorithm, RAG)', completed: false },
      { id: 'os-4', name: 'Memory mgmt (paging, TLB, virtual memory)', completed: false },
      { id: 'os-5', name: 'Page replacement (LRU, LFU, optimal) + disk scheduling', completed: false },
    ],
  },
  {
    id: 'dbms',
    name: 'Databases',
    shortName: 'DBMS',
    priority: 'P0',
    status: 'weak',
    weightage: '6-8',
    targetMarks: '5-7',
    resource: 'Korth & Navathe + Made Easy workbook',
    color: SUBJECT_COLORS.dbms,
    mustMasterTopics: [
      { id: 'db-1', name: 'ER model & relational algebra', completed: false },
      { id: 'db-2', name: 'SQL (nested, aggregation, joins, NULL)', completed: false },
      { id: 'db-3', name: 'Normalisation (1NF to BCNF, lossless, dependency)', completed: false },
      { id: 'db-4', name: 'Functional dependency closure', completed: false },
      { id: 'db-5', name: 'Transactions (serialisability, 2PL, recovery)', completed: false },
    ],
  },
  {
    id: 'networks',
    name: 'Computer Networks',
    shortName: 'Networks',
    priority: 'P0',
    status: 'weak',
    weightage: '6-8',
    targetMarks: '5-6',
    resource: 'Forouzan / Tanenbaum + Made Easy workbook',
    color: SUBJECT_COLORS.networks,
    mustMasterTopics: [
      { id: 'cn-1', name: 'OSI vs TCP/IP layer mapping', completed: false },
      { id: 'cn-2', name: 'Error detection (CRC, Hamming) & sliding window', completed: false },
      { id: 'cn-3', name: 'CSMA/CD, CSMA/CA, Ethernet frame', completed: false },
      { id: 'cn-4', name: 'IP addressing & subnetting (CIDR)', completed: false },
      { id: 'cn-5', name: 'TCP congestion control + application layer (DNS, HTTP)', completed: false },
    ],
  },
  {
    id: 'aptitude',
    name: 'General Aptitude',
    shortName: 'Aptitude',
    priority: 'P2',
    status: 'moderate',
    weightage: '15',
    targetMarks: '12-14',
    resource: 'R.S. Aggarwal + Made Easy aptitude workbook',
    color: SUBJECT_COLORS.aptitude,
    mustMasterTopics: [
      { id: 'ap-1', name: 'Numerical (percentages, ratios, time-speed, SI/CI)', completed: false },
      { id: 'ap-2', name: 'Logical reasoning (series, coding, blood relations)', completed: false },
      { id: 'ap-3', name: 'Spatial reasoning (cubes, paper folding)', completed: false },
      { id: 'ap-4', name: 'Verbal (grammar, vocab, RC)', completed: false },
    ],
  },
];

export const PHASES: PhaseInfo[] = [
  {
    id: 1,
    name: 'Foundation Rebuild',
    window: 'Jul - Sep 2026',
    from: '2026-07-01',
    to: '2026-09-30',
    goal: 'Rebuild conceptual foundations in Math, Discrete, Algorithms Part-1. Complete Digital Logic + Data Structures first pass.',
    weeklyHours: 28,
    milestones: [
      'Weeks 1-4: Engineering Mathematics complete (80 PYQs)',
      'Weeks 5-7: Discrete Mathematics complete (60 PYQs)',
      'Weeks 5-6: Digital Logic complete (40 PYQs)',
      'Weeks 8-12: Data Structures + Algorithms Part-1 (120 PYQs)',
      'Sep 30 milestone mock: 32+/65 target',
    ],
  },
  {
    id: 2,
    name: 'Subject Mastery',
    window: 'Oct - Nov 2026',
    from: '2026-10-01',
    to: '2026-11-30',
    goal: 'Complete COA, OS, DBMS, TOC, Compiler, Networks, Algorithms Part-2. Begin subject-wise mocks.',
    weeklyHours: 30,
    milestones: [
      'Weeks 13-14: COA (pipelining, cache, addressing modes)',
      'Weeks 13-16: Operating System (70 PYQs)',
      'Weeks 15-16: TOC (50 PYQs)',
      'Weeks 17-18: DBMS (60 PYQs) + Compiler (40 PYQs)',
      'Weeks 19-20: Networks (60 PYQs) + Algorithms Part-2 (40 PYQs)',
    ],
  },
  {
    id: 3,
    name: 'Revision + Test Series',
    window: 'Dec 2026 - mid Jan 2027',
    from: '2026-12-01',
    to: '2027-01-15',
    goal: 'Convert first-pass knowledge into exam-ready reflex. 2 full mocks per week + analysis. Target 50+.',
    weeklyHours: 30,
    milestones: [
      'Weekly: 2 full-length GATE-pattern mocks',
      'Each mock: 3-hour analysis session (silly/conceptual/time)',
      'Re-solve all marked PYQs from Phase 1 & 2',
      'Target by end-Dec: 50-58 marks (~rank 2,500)',
      'Target by mid-Jan: 55-62 marks (~rank 1,500)',
    ],
  },
  {
    id: 4,
    name: 'Final Mock Sprint',
    window: 'mid-Jan - Feb 2027',
    from: '2027-01-16',
    to: '2027-02-06',
    goal: 'Peak at the right time. 3 mocks per week, full revision. No new topics after Jan 25.',
    weeklyHours: 28,
    milestones: [
      '3 mocks per week + analysis',
      'Strict rule: no new topics after Jan 25',
      '5 days before exam: stop new mocks, review mistake log',
      'Last 5 days: formula revision + aptitude + sleep',
      'GATE 2027: 60-65+ marks (rank <1,500)',
    ],
  },
];

// Mock score -> rank correlation
export const MOCK_RANK_TABLE = [
  { min: 65, max: 100, rank: '< 500', tier: 'Tier 1 - Best' },
  { min: 60, max: 65, rank: '500 - 1,500', tier: 'Tier 1 - Best' },
  { min: 55, max: 60, rank: '1,500 - 3,000', tier: 'Tier 2 - Good' },
  { min: 50, max: 55, rank: '3,000 - 5,000', tier: 'Tier 2 - Good' },
  { min: 45, max: 50, rank: '5,000 - 10,000', tier: 'Tier 3 - Acceptable' },
  { min: 40, max: 45, rank: '10,000 - 15,000', tier: 'Tier 4 - Backup' },
  { min: 0, max: 40, rank: '> 15,000', tier: 'Tier 5 - Repeat' },
];

export function scoreToRank(score: number) {
  return MOCK_RANK_TABLE.find(t => score >= t.min && score < t.max) ?? MOCK_RANK_TABLE[MOCK_RANK_TABLE.length - 1];
}

// PSU exam info
export const PSU_EXAMS = [
  {
    id: 'gate',
    name: 'GATE CSE 2027',
    conductingBody: 'IISc Bangalore / IIT (rotational)',
    notificationMonth: 'Sep 2026',
    examMonth: 'Feb 6-7, 2027',
    duration: '180 min',
    totalQuestions: 65,
    maxMarks: 100,
    negativeMarking: '1/3 (1-mark) & 2/3 (2-mark)',
    entryRoute: 'Direct',
    interviewWeight: 'N/A',
    syllabusDelta: 'Base',
    officialSite: 'https://gate.iisc.ac.in',
    color: 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/30',
  },
  {
    id: 'barc',
    name: 'BARC Scientist-D',
    conductingBody: 'Bhabha Atomic Research Centre',
    notificationMonth: 'Jan - Feb 2027',
    examMonth: 'Mar - Apr 2027',
    duration: '120 min',
    totalQuestions: 100,
    maxMarks: 100,
    negativeMarking: '-1 (typical)',
    entryRoute: 'GATE or own exam',
    interviewWeight: '~80%',
    syllabusDelta: 'Slight (more Math/CO)',
    officialSite: 'https://barc.gov.in',
    color: 'border-amber-500 bg-amber-50 dark:bg-amber-950/30',
  },
  {
    id: 'nic',
    name: 'NIC Scientist-B',
    conductingBody: 'National Informatics Centre',
    notificationMonth: 'Mar - Apr 2027',
    examMonth: 'May - Jun 2027',
    duration: '120 min',
    totalQuestions: 78,
    maxMarks: 120,
    negativeMarking: '1/4 mark',
    entryRoute: 'Own exam',
    interviewWeight: '~15%',
    syllabusDelta: 'Moderate (SE, Web, IS, Cloud)',
    officialSite: 'https://www.nic.in',
    color: 'border-violet-500 bg-violet-50 dark:bg-violet-950/30',
  },
  {
    id: 'isro',
    name: 'ISRO Scientist/Engineer-SC',
    conductingBody: 'Indian Space Research Organisation',
    notificationMonth: 'Feb - Mar 2027',
    examMonth: 'Apr - May 2027',
    duration: '90 min',
    totalQuestions: 80,
    maxMarks: 240,
    negativeMarking: '-1 mark',
    entryRoute: 'Own exam',
    interviewWeight: '~50%',
    syllabusDelta: 'Slight (more DL/CO/Math)',
    officialSite: 'https://www.isro.gov.in',
    color: 'border-rose-500 bg-rose-50 dark:bg-rose-950/30',
  },
];

export const SEED_CHEAT_SHEET: CheatSheetItem[] = [
  // Engineering Mathematics
  { id: 'cs-em-1', subject: 'Engineering Mathematics', name: 'Eigenvalues', formula: '\\text{Sum} = \\text{trace}, \\quad \\text{Product} = \\det(A)', mastered: false, difficulty: 'must-know', example: 'For A = [[2,1],[1,2]], trace=4, det=3. Eigenvalues are 3 and 1.' },
  { id: 'cs-em-2', subject: 'Engineering Mathematics', name: 'Conditional Probability', formula: 'P(A|B) = \\frac{P(A \\cap B)}{P(B)}', mastered: false, difficulty: 'must-know', example: 'If P(cloud)=0.4 and P(rain∩cloud)=0.3, then P(rain|cloud)=0.3/0.4=0.75' },
  { id: 'cs-em-3', subject: 'Engineering Mathematics', name: 'Bayes Theorem', formula: 'P(A|B) = \\frac{P(B|A)P(A)}{P(B)}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-em-4', subject: 'Engineering Mathematics', name: 'Binomial Distribution', formula: '\\text{Mean} = np, \\quad \\text{Variance} = np(1-p)', mastered: false, difficulty: 'must-know' },
  { id: 'cs-em-5', subject: 'Engineering Mathematics', name: 'Poisson Distribution', formula: '\\text{Mean} = \\text{Variance} = \\lambda', mastered: false, difficulty: 'frequent' },
  { id: 'cs-em-6', subject: 'Engineering Mathematics', name: 'Normal Distribution (68-95-99.7)', formula: 'P(|X-\\mu|<\\sigma) \\approx 68\\%, <2\\sigma \\approx 95\\%, <3\\sigma \\approx 99.7\\%', mastered: false, difficulty: 'must-know' },
  { id: 'cs-em-7', subject: 'Engineering Mathematics', name: 'Newton-Raphson', formula: 'x_{n+1} = x_n - \\frac{f(x_n)}{f\'(x_n)}', mastered: false, difficulty: 'frequent' },
  // Discrete Mathematics
  { id: 'cs-dm-1', subject: 'Discrete Mathematics', name: 'Logical Equivalence', formula: 'p \\to q \\equiv \\lnot p \\lor q \\equiv \\lnot q \\to \\lnot p', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dm-2', subject: 'Discrete Mathematics', name: 'Derangements', formula: 'D(n) = n! \\sum_{k=0}^n \\frac{(-1)^k}{k!}', mastered: false, difficulty: 'tricky' },
  { id: 'cs-dm-3', subject: 'Discrete Mathematics', name: 'Pigeonhole Principle', formula: 'n \\text{ items into } m \\text{ boxes, } n>m \\implies \\exists \\text{ box with } \\ge \\lceil n/m \\rceil \\text{ items}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dm-4', subject: 'Discrete Mathematics', name: "Euler's Formula (planar)", formula: 'V - E + F = 2', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dm-5', subject: 'Discrete Mathematics', name: 'Handshaking Lemma', formula: '\\sum \\deg(v) = 2|E|', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dm-6', subject: 'Discrete Mathematics', name: 'Chromatic Polynomial (tree)', formula: 'P(k) = k(k-1)^{n-1} \\text{ for tree on } n \\text{ vertices}', mastered: false, difficulty: 'tricky' },
  // Digital Logic & COA
  { id: 'cs-dl-1', subject: 'Digital Logic & COA', name: "2s Complement Range", formula: '-2^{n-1} \\text{ to } 2^{n-1}-1 \\text{ for } n \\text{ bits}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dl-2', subject: 'Digital Logic & COA', name: 'IEEE 754 Single Precision', formula: '\\text{sign}(1) + \\text{exponent}(8, \\text{bias }127) + \\text{mantissa}(23)', mastered: false, difficulty: 'frequent' },
  { id: 'cs-dl-3', subject: 'Digital Logic & COA', name: 'Cache Access Time', formula: 'T_{\\text{avg}} = t_{\\text{hit}} + \\text{miss rate} \\times \\text{miss penalty}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-dl-4', subject: 'Digital Logic & COA', name: 'Pipeline Speedup', formula: 'S = \\frac{n \\cdot t}{t + (n-1) \\cdot c}, \\quad t=\\text{stage time}, c=\\text{clock cycle}', mastered: false, difficulty: 'frequent' },
  { id: 'cs-dl-5', subject: 'Digital Logic & COA', name: "Amdahl's Law", formula: 'S = \\frac{1}{(1-p) + p/N}, \\quad p = \\text{parallelisable fraction}', mastered: false, difficulty: 'must-know' },
  // Data Structures & Algorithms
  { id: 'cs-al-1', subject: 'Data Structures & Algorithms', name: 'Master Theorem', formula: 'T(n) = aT(n/b) + f(n). \\text{ Compare } f(n) \\text{ vs } n^{\\log_b a}', mastered: false, difficulty: 'must-know', code: '// Case 1: f(n) = O(n^(log_b a - ε)) → T(n) = Θ(n^(log_b a))\n// Case 2: f(n) = Θ(n^(log_b a) log^k n) → T(n) = Θ(n^(log_b a) log^(k+1) n)\n// Case 3: f(n) = Ω(n^(log_b a + ε)) & af(n/b) ≤ cf(n) → T(n) = Θ(f(n))' },
  { id: 'cs-al-2', subject: 'Data Structures & Algorithms', name: 'Sorting Complexities', formula: '\\begin{array}{ll}\\text{Merge: } & O(n \\log n) \\text{ all} \\\\ \\text{Quick: } & O(n^2) \\text{ worst}, O(n \\log n) \\text{ avg} \\\\ \\text{Heap: } & O(n \\log n) \\text{ all} \\\\ \\text{Radix: } & O(nk) \\end{array}', mastered: false, difficulty: 'must-know', code: '// Quick sort partition\nint partition(int arr[], int lo, int hi) {\n  int pivot = arr[hi], i = lo - 1;\n  for (int j = lo; j < hi; j++)\n    if (arr[j] <= pivot) swap(&arr[++i], &arr[j]);\n  swap(&arr[i+1], &arr[hi]);\n  return i+1;\n}' },
  { id: 'cs-al-3', subject: 'Data Structures & Algorithms', name: 'BST Operations', formula: '\\text{search/insert/delete} = O(h), \\text{balanced: } O(\\log n)', mastered: false, difficulty: 'must-know', code: '// BST search\nNode* search(Node* root, int key) {\n  if (!root || root->key == key) return root;\n  if (key < root->key) return search(root->left, key);\n  return search(root->right, key);\n}' },
  { id: 'cs-al-4', subject: 'Data Structures & Algorithms', name: 'Hashing Load Factor', formula: '\\alpha = n/m; \\text{ Chaining: } O(1+\\alpha); \\text{ Open addressing: } O(1/(1-\\alpha))', mastered: false, difficulty: 'frequent' },
  { id: 'cs-al-5', subject: 'Data Structures & Algorithms', name: 'Dijkstra', formula: 'O((V+E) \\log V) \\text{ with binary heap}', mastered: false, difficulty: 'must-know', code: '// Dijkstra\nvector<int> dist(n, INF); dist[s] = 0;\npriority_queue<pi, vector<pi>, greater<>> pq; pq.push({0,s});\nwhile (!pq.empty()) {\n  auto [d,u] = pq.top(); pq.pop();\n  if (d != dist[u]) continue;\n  for (auto [v,w] : adj[u])\n    if (dist[u] + w < dist[v])\n      dist[v] = dist[u] + w, pq.push({dist[v], v});\n}' },
  { id: 'cs-al-6', subject: 'Data Structures & Algorithms', name: 'Bellman-Ford', formula: 'O(VE)', mastered: false, difficulty: 'frequent', code: '// Bellman-Ford\nfor (int i = 0; i < n-1; i++)\n  for (auto [u,v,w] : edges)\n    if (dist[u] != INF && dist[u] + w < dist[v])\n      dist[v] = dist[u] + w;' },
  { id: 'cs-al-7', subject: 'Data Structures & Algorithms', name: 'Floyd-Warshall', formula: 'O(V^3)', mastered: false, difficulty: 'frequent', code: '// Floyd-Warshall\nfor (int k = 0; k < n; k++)\n  for (int i = 0; i < n; i++)\n    for (int j = 0; j < n; j++)\n      dist[i][j] = min(dist[i][j], dist[i][k] + dist[k][j]);' },
  { id: 'cs-al-8', subject: 'Data Structures & Algorithms', name: '0/1 Knapsack DP', formula: 'O(nW)', mastered: false, difficulty: 'must-know', code: '// 0/1 Knapsack\nint dp[W+1] = {0};\nfor (int i = 0; i < n; i++)\n  for (int w = W; w >= wt[i]; w--)\n    dp[w] = max(dp[w], dp[w-wt[i]] + val[i]);' },
  { id: 'cs-al-9', subject: 'Data Structures & Algorithms', name: 'LCS / Edit Distance', formula: 'O(mn)', mastered: false, difficulty: 'frequent', code: '// LCS\nfor (int i = 1; i <= m; i++)\n  for (int j = 1; j <= n; j++)\n    if (a[i-1] == b[j-1]) dp[i][j] = dp[i-1][j-1] + 1;\n    else dp[i][j] = max(dp[i-1][j], dp[i][j-1]);' },
  { id: 'cs-al-10', subject: 'Data Structures & Algorithms', name: 'Matrix Chain DP', formula: 'O(n^3)', mastered: false, difficulty: 'tricky', code: '// MCM\nfor (int len = 2; len <= n; len++)\n  for (int i = 1; i <= n-len+1; i++) {\n    int j = i+len-1; dp[i][j] = INF;\n    for (int k = i; k < j; k++)\n      dp[i][j] = min(dp[i][j], dp[i][k] + dp[k+1][j] + p[i-1]*p[k]*p[j]);\n  }' },
  // Operating System
  { id: 'cs-os-1', subject: 'Operating System', name: 'Page Replacement Anomaly', formula: '\\text{FIFO has Belady anomaly; LRU optimal among stack algorithms}', mastered: false, difficulty: 'frequent' },
  { id: 'cs-os-2', subject: 'Operating System', name: "Banker's Algorithm", formula: '\\text{Safe if } \\exists P_i: \\text{Work} \\ge \\text{Need}_i; \\text{ then Work += Alloc}_i, \\text{ repeat}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-os-3', subject: 'Operating System', name: 'TLB Effective Access Time', formula: '\\text{EAT} = h \\cdot t_{\\text{tlb}} + (1-h) \\cdot (t_{\\text{tlb}} + 2 \\cdot t_{\\text{mem}})', mastered: false, difficulty: 'must-know' },
  { id: 'cs-os-4', subject: 'Operating System', name: 'CPU Scheduling', formula: '\\begin{array}{ll}\\text{SJF:} & \\text{sort by burst, shorter first} \\\\ \\text{SRTF:} & \\text{preemptive, track remaining time} \\\\ \\text{RR:} & TQ \\text{ critical; too large=FCFS, too small=overhead} \\end{array}', mastered: false, difficulty: 'must-know' },
  // DBMS / TOC / Compiler / Networks
  { id: 'cs-oth-1', subject: 'DBMS / TOC / Compiler / Networks', name: 'Normalisation', formula: '\\text{1NF: atomic; 2NF: no partial dep; 3NF: no transitive dep; BCNF: every det. is superkey}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-oth-2', subject: 'DBMS / TOC / Compiler / Networks', name: 'Conflict Serialisability', formula: '\\text{Precedence graph acyclic} \\iff \\text{conflict serialisable}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-oth-3', subject: 'DBMS / TOC / Compiler / Networks', name: '2PL Protocol', formula: '\\text{Strict 2PL = growing + shrinking} + \\text{release at commit. Prevents cascading aborts}', mastered: false, difficulty: 'frequent' },
  { id: 'cs-oth-4', subject: 'DBMS / TOC / Compiler / Networks', name: 'Regular Language Closure', formula: '\\text{Closed under } \\cup, \\cap, \\overline{(\\;)}, \\circ, ^*, \\text{homomorphism}', mastered: false, difficulty: 'must-know' },
  { id: 'cs-oth-5', subject: 'DBMS / TOC / Compiler / Networks', name: 'Pumping Lemma (regular)', formula: '\\exists p \\; \\forall w \\in L, |w| \\ge p: w=xyz, |xy| \\le p, |y|>0, \\forall i \\ge 0: xy^iz \\in L', mastered: false, difficulty: 'must-know' },
  { id: 'cs-oth-6', subject: 'DBMS / TOC / Compiler / Networks', name: 'LL(1) Grammar Conditions', formula: '\\text{No FIRST/FOLLOW conflict, no left recursion, no common prefix}', mastered: false, difficulty: 'frequent' },
  { id: 'cs-oth-7', subject: 'DBMS / TOC / Compiler / Networks', name: 'Subnetting', formula: '\\text{Hosts} = 2^h - 2; \\quad \\text{Subnets} = 2^s', mastered: false, difficulty: 'must-know' },
  { id: 'cs-oth-8', subject: 'DBMS / TOC / Compiler / Networks', name: 'TCP Slow Start', formula: '\\text{cwnd doubles per RTT (grows by 1 per ACK received)}', mastered: false, difficulty: 'frequent' },
  { id: 'cs-oth-9', subject: 'DBMS / TOC / Compiler / Networks', name: 'TCP Congestion Avoidance (AIMD)', formula: '\\text{cwnd += 1/cwnd per ACK (linear growth per RTT). On loss: cwnd /= 2}', mastered: false, difficulty: 'frequent' },
];

function makeCheatSheetItem(
  id: string,
  subject: string,
  name: string,
  formula: string,
  difficulty: CheatSheetDifficulty = 'frequent',
  tags: string[] = [],
  extra: Partial<Pick<CheatSheetItem, 'example' | 'code' | 'notes'>> = {}
): CheatSheetItem {
  return {
    id,
    subject,
    name,
    formula,
    mastered: false,
    difficulty,
    tags,
    ...extra,
  };
}

export const SEED_CHEAT_SHEET_V2: CheatSheetItem[] = [
  makeCheatSheetItem('cs-em-1', 'Engineering Mathematics', 'Eigenvalues', '\\text{sum}=\\operatorname{trace}(A), \\quad \\text{product}=\\det(A)', 'must-know', ['linear-algebra'], { example: 'For [[2,1],[1,2]], trace=4 and det=3, so eigenvalues are 3 and 1.' }),
  makeCheatSheetItem('cs-em-2', 'Engineering Mathematics', 'Conditional Probability', 'P(A|B)=\\frac{P(A \\cap B)}{P(B)}', 'must-know', ['probability']),
  makeCheatSheetItem('cs-em-3', 'Engineering Mathematics', 'Bayes Theorem', 'P(A_i|B)=\\frac{P(B|A_i)P(A_i)}{\\sum_j P(B|A_j)P(A_j)}', 'must-know', ['probability']),
  makeCheatSheetItem('cs-em-4', 'Engineering Mathematics', 'Binomial Distribution', 'P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}, \\quad E[X]=np, \\quad Var(X)=np(1-p)', 'must-know', ['probability']),
  makeCheatSheetItem('cs-em-5', 'Engineering Mathematics', 'Poisson Distribution', 'P(X=k)=e^{-\\lambda}\\frac{\\lambda^k}{k!}, \\quad E[X]=Var(X)=\\lambda', 'frequent', ['probability']),
  makeCheatSheetItem('cs-em-6', 'Engineering Mathematics', 'Normal Distribution Rule', 'P(|X-\\mu|<\\sigma)\\approx0.68, \\quad P(|X-\\mu|<2\\sigma)\\approx0.95, \\quad P(|X-\\mu|<3\\sigma)\\approx0.997', 'frequent', ['statistics']),
  makeCheatSheetItem('cs-em-7', 'Engineering Mathematics', 'Newton-Raphson', "x_{n+1}=x_n-\\frac{f(x_n)}{f'(x_n)}", 'frequent', ['numerical-methods']),
  makeCheatSheetItem('cs-em-8', 'Engineering Mathematics', 'Rank Nullity', '\\operatorname{rank}(A)+\\operatorname{nullity}(A)=n', 'must-know', ['linear-algebra']),
  makeCheatSheetItem('cs-em-9', 'Engineering Mathematics', 'Trapezoidal Rule', '\\int_a^b f(x)dx \\approx \\frac{h}{2}\\left[y_0+y_n+2\\sum_{i=1}^{n-1}y_i\\right]', 'frequent', ['numerical-methods']),
  makeCheatSheetItem('cs-em-10', 'Engineering Mathematics', "Simpson's 1/3 Rule", '\\int_a^b f(x)dx \\approx \\frac{h}{3}\\left[y_0+y_n+4\\sum y_{odd}+2\\sum y_{even}\\right]', 'tricky', ['numerical-methods']),
  makeCheatSheetItem('cs-em-11', 'Engineering Mathematics', 'Covariance And Correlation', 'Cov(X,Y)=E[XY]-E[X]E[Y], \\quad \\rho=\\frac{Cov(X,Y)}{\\sigma_X\\sigma_Y}', 'frequent', ['statistics']),

  makeCheatSheetItem('cs-dm-1', 'Discrete Mathematics', 'Implication Equivalence', 'p \\to q \\equiv \\neg p \\lor q \\equiv \\neg q \\to \\neg p', 'must-know', ['logic']),
  makeCheatSheetItem('cs-dm-2', 'Discrete Mathematics', 'Derangements', '!n=n!\\sum_{k=0}^{n}\\frac{(-1)^k}{k!}\\approx\\frac{n!}{e}', 'tricky', ['counting']),
  makeCheatSheetItem('cs-dm-3', 'Discrete Mathematics', 'Pigeonhole Principle', 'n \\text{ objects in } m \\text{ boxes} \\Rightarrow \\text{some box has at least } \\lceil n/m \\rceil', 'must-know', ['counting']),
  makeCheatSheetItem('cs-dm-4', 'Discrete Mathematics', "Euler's Formula For Planar Graphs", 'V-E+F=2', 'must-know', ['graph-theory']),
  makeCheatSheetItem('cs-dm-5', 'Discrete Mathematics', 'Handshaking Lemma', '\\sum_{v\\in V}\\deg(v)=2|E|', 'must-know', ['graph-theory']),
  makeCheatSheetItem('cs-dm-6', 'Discrete Mathematics', 'Chromatic Polynomial Of Tree', 'P_T(k)=k(k-1)^{n-1}', 'tricky', ['graph-theory']),
  makeCheatSheetItem('cs-dm-7', 'Discrete Mathematics', 'Inclusion Exclusion', '|A\\cup B\\cup C|=|A|+|B|+|C|-|AB|-|BC|-|CA|+|ABC|', 'must-know', ['counting']),
  makeCheatSheetItem('cs-dm-8', 'Discrete Mathematics', 'Relations Count', '\\text{relations from } A \\text{ to } B = 2^{|A||B|}', 'frequent', ['relations']),
  makeCheatSheetItem('cs-dm-9', 'Discrete Mathematics', 'Onto Functions', '\\sum_{i=0}^{m}(-1)^i\\binom{m}{i}(m-i)^n', 'tricky', ['functions']),
  makeCheatSheetItem('cs-dm-10', 'Discrete Mathematics', "Lagrange's Theorem", 'H\\le G \\Rightarrow |H| \\text{ divides } |G|', 'frequent', ['group-theory']),

  makeCheatSheetItem('cs-dl-1', 'Digital Logic', "2s Complement Range", '-2^{n-1} \\text{ to } 2^{n-1}-1', 'must-know', ['number-system']),
  makeCheatSheetItem('cs-dl-2', 'Digital Logic', 'IEEE 754 Single Precision', '\\text{sign}=1, \\quad \\text{exponent}=8 \\text{ with bias }127, \\quad \\text{mantissa}=23', 'frequent', ['floating-point']),
  makeCheatSheetItem('cs-dl-6', 'Digital Logic', 'Boolean Algebra Core Laws', 'A+AB=A, \\quad A(A+B)=A, \\quad A+\\bar{A}B=A+B', 'must-know', ['boolean-algebra']),
  makeCheatSheetItem('cs-dl-7', 'Digital Logic', 'De Morgan Laws', '\\overline{AB}=\\bar A+\\bar B, \\quad \\overline{A+B}=\\bar A\\bar B', 'must-know', ['boolean-algebra']),
  makeCheatSheetItem('cs-dl-8', 'Digital Logic', 'Full Adder', 'S=A\\oplus B\\oplus C_{in}, \\quad C_{out}=AB+BC_{in}+AC_{in}', 'must-know', ['combinational']),
  makeCheatSheetItem('cs-dl-9', 'Digital Logic', 'Flip-Flop Excitation', '\\text{JK: }0\\to1:J=1, \\; 1\\to0:K=1; \\quad \\text{T toggles when }T=1', 'frequent', ['sequential']),
  makeCheatSheetItem('cs-dl-10', 'Digital Logic', 'K-Map Group Sizes', '\\text{groups are powers of two: }1,2,4,8,16; \\quad \\text{use largest groups first}', 'must-know', ['k-map']),

  makeCheatSheetItem('cs-dl-3', 'Computer Organisation & Architecture', 'Average Memory Access Time', 'AMAT=t_{hit}+\\text{miss rate}\\times\\text{miss penalty}', 'must-know', ['cache']),
  makeCheatSheetItem('cs-dl-4', 'Computer Organisation & Architecture', 'Pipeline Speedup', 'S\\approx\\frac{k n \\tau}{(k+n-1)\\tau}', 'frequent', ['pipeline']),
  makeCheatSheetItem('cs-dl-5', 'Computer Organisation & Architecture', "Amdahl's Law", 'S=\\frac{1}{(1-p)+p/N}', 'must-know', ['performance']),
  makeCheatSheetItem('cs-coa-1', 'Computer Organisation & Architecture', 'CPU Execution Time', 'T=IC\\times CPI\\times\\text{clock cycle time}=\\frac{IC\\times CPI}{\\text{clock rate}}', 'must-know', ['performance']),
  makeCheatSheetItem('cs-coa-2', 'Computer Organisation & Architecture', 'CPI With Instruction Mix', 'CPI_{avg}=\\sum_i f_i\\times CPI_i', 'must-know', ['performance']),
  makeCheatSheetItem('cs-coa-3', 'Computer Organisation & Architecture', 'Cache Address Split', '\\text{address bits}=\\text{tag}+\\text{index}+\\text{block offset}', 'must-know', ['cache']),
  makeCheatSheetItem('cs-coa-4', 'Computer Organisation & Architecture', 'Set Associative Cache Sets', '\\text{sets}=\\frac{\\text{cache size}}{\\text{block size}\\times\\text{associativity}}', 'frequent', ['cache']),
  makeCheatSheetItem('cs-coa-5', 'Computer Organisation & Architecture', 'Virtual Address Split', '\\text{virtual address}=\\text{virtual page number}+\\text{page offset}', 'frequent', ['virtual-memory']),

  makeCheatSheetItem('cs-al-3', 'Programming & Data Structures', 'BST Operations', '\\text{search/insert/delete}=O(h), \\quad \\text{balanced}=O(\\log n), \\quad \\text{skewed}=O(n)', 'must-know', ['tree'], { code: 'Node* search(Node* root, int key) {\n  if (!root || root->key == key) return root;\n  return key < root->key ? search(root->left, key) : search(root->right, key);\n}' }),
  makeCheatSheetItem('cs-al-4', 'Programming & Data Structures', 'Hashing Load Factor', '\\alpha=\\frac{n}{m}; \\quad \\text{chaining avg}=O(1+\\alpha)', 'frequent', ['hashing']),
  makeCheatSheetItem('cs-ds-1', 'Programming & Data Structures', 'Row Major Address', 'addr(A[i][j])=base+w((i-L_r)n+(j-L_c))', 'must-know', ['arrays']),
  makeCheatSheetItem('cs-ds-2', 'Programming & Data Structures', 'Column Major Address', 'addr(A[i][j])=base+w((j-L_c)m+(i-L_r))', 'frequent', ['arrays']),
  makeCheatSheetItem('cs-ds-3', 'Programming & Data Structures', 'Heap Index Rules', '\\text{parent}(i)=\\lfloor(i-1)/2\\rfloor, \\quad left=2i+1, \\quad right=2i+2', 'must-know', ['heap']),
  makeCheatSheetItem('cs-ds-4', 'Programming & Data Structures', 'AVL Height Recurrence', 'N(h)=1+N(h-1)+N(h-2), \\quad h=O(\\log n)', 'tricky', ['avl']),
  makeCheatSheetItem('cs-ds-5', 'Programming & Data Structures', 'Graph Storage', '\\text{matrix}=O(V^2), \\quad \\text{list}=O(V+E)', 'must-know', ['graphs']),
  makeCheatSheetItem('cs-ds-6', 'Programming & Data Structures', 'DFS And BFS Time', 'O(V+E) \\text{ with adjacency list}', 'must-know', ['graphs']),

  makeCheatSheetItem('cs-al-1', 'Algorithms', 'Master Theorem', 'T(n)=aT(n/b)+f(n), \\quad \\text{compare } f(n) \\text{ with } n^{\\log_b a}', 'must-know', ['recurrence'], { code: 'Case 1: f(n)=O(n^(log_b a - eps)) => T(n)=Theta(n^(log_b a))\nCase 2: f(n)=Theta(n^(log_b a) log^k n) => T(n)=Theta(n^(log_b a) log^(k+1)n)\nCase 3: f(n)=Omega(n^(log_b a + eps)) and regularity holds => T(n)=Theta(f(n))' }),
  makeCheatSheetItem('cs-al-2', 'Algorithms', 'Sorting Complexities', '\\text{merge}=O(n\\log n), \\quad \\text{quick avg}=O(n\\log n), \\quad \\text{quick worst}=O(n^2), \\quad \\text{heap}=O(n\\log n)', 'must-know', ['sorting']),
  makeCheatSheetItem('cs-al-5', 'Algorithms', 'Dijkstra', 'O((V+E)\\log V) \\text{ with binary heap, non-negative edges only}', 'must-know', ['shortest-path']),
  makeCheatSheetItem('cs-al-6', 'Algorithms', 'Bellman-Ford', 'O(VE), \\quad \\text{relax all edges } V-1 \\text{ times}', 'frequent', ['shortest-path']),
  makeCheatSheetItem('cs-al-7', 'Algorithms', 'Floyd-Warshall', 'O(V^3), \\quad d[i][j]=\\min(d[i][j], d[i][k]+d[k][j])', 'frequent', ['shortest-path']),
  makeCheatSheetItem('cs-al-8', 'Algorithms', '0/1 Knapsack DP', 'O(nW), \\quad dp[w]=\\max(dp[w], dp[w-w_i]+v_i)', 'must-know', ['dp']),
  makeCheatSheetItem('cs-al-9', 'Algorithms', 'LCS DP', 'dp[i][j]=1+dp[i-1][j-1] \\text{ if match, else } \\max(dp[i-1][j],dp[i][j-1])', 'frequent', ['dp']),
  makeCheatSheetItem('cs-al-10', 'Algorithms', 'Matrix Chain Multiplication', 'dp[i][j]=\\min_{i\\le k<j}(dp[i][k]+dp[k+1][j]+p_{i-1}p_kp_j)', 'tricky', ['dp']),
  makeCheatSheetItem('cs-al-11', 'Algorithms', 'Kruskal MST', 'O(E\\log E), \\quad \\text{sort edges and union components}', 'must-know', ['mst']),
  makeCheatSheetItem('cs-al-12', 'Algorithms', 'NP-Completeness Pattern', 'A\\in NP \\text{ and } B\\le_p A \\text{ for known NP-complete }B \\Rightarrow A\\text{ is NP-complete}', 'tricky', ['np-completeness']),

  makeCheatSheetItem('cs-oth-4', 'Theory of Computation', 'Regular Language Closure', '\\text{closed under union, intersection, complement, concatenation, star, reversal}', 'must-know', ['regular-language']),
  makeCheatSheetItem('cs-oth-5', 'Theory of Computation', 'Pumping Lemma For Regular Languages', '\\exists p\\;\\forall w\\in L, |w|\\ge p: w=xyz, |xy|\\le p, |y|>0, \\forall i\\ge0:xy^iz\\in L', 'must-know', ['pumping-lemma']),
  makeCheatSheetItem('cs-toc-1', 'Theory of Computation', 'DFA Transition Function', '\\delta:Q\\times\\Sigma\\to Q', 'must-know', ['dfa']),
  makeCheatSheetItem('cs-toc-2', 'Theory of Computation', 'NFA To DFA Bound', 'n \\text{ NFA states } \\Rightarrow \\text{ up to }2^n \\text{ DFA states}', 'must-know', ['nfa']),
  makeCheatSheetItem('cs-toc-3', 'Theory of Computation', "Arden's Lemma", 'R=Q+RP \\Rightarrow R=QP^* \\quad \\text{if }\\epsilon\\notin P', 'frequent', ['regular-expression']),
  makeCheatSheetItem('cs-toc-4', 'Theory of Computation', 'CNF Form', 'A\\to BC \\text{ or } A\\to a \\quad (S\\to\\epsilon \\text{ only if needed})', 'frequent', ['cfg']),
  makeCheatSheetItem('cs-toc-5', 'Theory of Computation', 'Decidability Hierarchy', '\\text{regular}\\subset\\text{CFL}\\subset\\text{decidable}\\subset\\text{Turing-recognizable}', 'must-know', ['decidability']),

  makeCheatSheetItem('cs-oth-6', 'Compiler Design', 'LL(1) Conditions', '\\text{no left recursion, no common prefix, no FIRST/FIRST or FIRST/FOLLOW conflict}', 'must-know', ['parsing']),
  makeCheatSheetItem('cs-cd-1', 'Compiler Design', 'FIRST Set Rule', 'FIRST(\\alpha\\beta)=FIRST(\\alpha)-\\{\\epsilon\\}; \\text{ if }\\epsilon\\in FIRST(\\alpha), \\text{ add }FIRST(\\beta)', 'must-know', ['first-follow']),
  makeCheatSheetItem('cs-cd-2', 'Compiler Design', 'FOLLOW Set Rule', 'A\\to\\alpha B\\beta \\Rightarrow FIRST(\\beta)-\\{\\epsilon\\}\\subseteq FOLLOW(B)', 'must-know', ['first-follow']),
  makeCheatSheetItem('cs-cd-3', 'Compiler Design', 'LR(0) Closure', 'A\\to\\alpha .B\\beta \\Rightarrow \\text{add }B\\to .\\gamma \\text{ for each }B\\to\\gamma', 'frequent', ['lr-parsing']),
  makeCheatSheetItem('cs-cd-4', 'Compiler Design', 'SLR Conflict Check', '\\text{reduce } A\\to\\alpha \\text{ on } FOLLOW(A)', 'tricky', ['lr-parsing']),
  makeCheatSheetItem('cs-cd-5', 'Compiler Design', 'Three Address Code Quadruple', '(op,arg1,arg2,result)', 'frequent', ['intermediate-code']),
  makeCheatSheetItem('cs-cd-6', 'Compiler Design', 'Lexical Analyzer Pipeline', '\\text{regex}\\to\\text{NFA}\\to\\text{DFA}\\to\\text{minimized DFA}', 'must-know', ['lexical-analysis']),

  makeCheatSheetItem('cs-os-1', 'Operating System', 'Belady Anomaly', '\\text{FIFO may have more page faults with more frames; stack algorithms do not}', 'frequent', ['paging']),
  makeCheatSheetItem('cs-os-2', 'Operating System', "Banker's Algorithm", '\\text{Need}=\\text{Max}-\\text{Allocation}; \\quad \\text{safe if Need}\\le\\text{Work}', 'must-know', ['deadlock']),
  makeCheatSheetItem('cs-os-3', 'Operating System', 'TLB Effective Access Time', 'EAT=h(t_{TLB}+t_M)+(1-h)(t_{TLB}+2t_M)', 'must-know', ['memory-management']),
  makeCheatSheetItem('cs-os-4', 'Operating System', 'CPU Scheduling Metrics', 'TAT=CT-AT, \\quad WT=TAT-BT, \\quad RT=\\text{first response}-AT', 'must-know', ['scheduling']),
  makeCheatSheetItem('cs-os-5', 'Operating System', 'Semaphore Wait Signal', 'wait(S):S--; \\text{ block if }S<0; \\quad signal(S):S++; \\text{ wake if }S\\le0', 'must-know', ['synchronization']),
  makeCheatSheetItem('cs-os-6', 'Operating System', 'Deadlock Conditions', '\\text{mutual exclusion + hold and wait + no preemption + circular wait}', 'must-know', ['deadlock']),
  makeCheatSheetItem('cs-os-7', 'Operating System', 'Page Table Size', '\\text{entries}=\\frac{\\text{virtual address space}}{\\text{page size}}, \\quad \\text{size}=\\text{entries}\\times\\text{PTE size}', 'frequent', ['paging']),

  makeCheatSheetItem('cs-oth-1', 'Databases', 'Normal Forms', '\\text{1NF atomic; 2NF no partial dependency; 3NF no transitive dependency; BCNF every determinant is superkey}', 'must-know', ['normalization']),
  makeCheatSheetItem('cs-oth-2', 'Databases', 'Conflict Serialisability', '\\text{precedence graph acyclic}\\iff\\text{conflict serializable}', 'must-know', ['transactions']),
  makeCheatSheetItem('cs-oth-3', 'Databases', 'Strict 2PL', '\\text{growing + shrinking, exclusive locks released at commit}', 'frequent', ['transactions']),
  makeCheatSheetItem('cs-db-1', 'Databases', 'Attribute Closure', 'X^+=\\text{all attributes derivable from }X\\text{ using FDs}', 'must-know', ['functional-dependency']),
  makeCheatSheetItem('cs-db-2', 'Databases', 'Candidate Key Test', 'X \\text{ is key iff }X^+=R\\text{ and no proper subset determines }R', 'must-know', ['functional-dependency']),
  makeCheatSheetItem('cs-db-3', 'Databases', 'Lossless Join Test', 'R_1\\bowtie R_2 \\text{ lossless iff }(R_1\\cap R_2)\\to R_1 \\text{ or }(R_1\\cap R_2)\\to R_2', 'tricky', ['decomposition']),
  makeCheatSheetItem('cs-db-4', 'Databases', 'B+ Tree Height', 'h\\approx\\lceil\\log_f L\\rceil+1', 'frequent', ['indexing']),
  makeCheatSheetItem('cs-db-5', 'Databases', 'Selection Cardinality', '|\\sigma_{A=c}(R)|\\approx\\frac{|R|}{V(R,A)}', 'frequent', ['query-processing']),

  makeCheatSheetItem('cs-oth-7', 'Computer Networks', 'Subnet Hosts', '\\text{usable hosts}=2^h-2, \\quad \\text{subnets}=2^s', 'must-know', ['ip-addressing']),
  makeCheatSheetItem('cs-oth-8', 'Computer Networks', 'TCP Slow Start', '\\text{cwnd doubles every RTT until threshold or loss}', 'frequent', ['tcp']),
  makeCheatSheetItem('cs-oth-9', 'Computer Networks', 'TCP Congestion Avoidance', '\\text{AIMD: cwnd grows linearly; on loss, cwnd is reduced}', 'frequent', ['tcp']),
  makeCheatSheetItem('cs-cn-1', 'Computer Networks', 'Bandwidth Delay Product', 'BDP=\\text{bandwidth}\\times RTT', 'must-know', ['transport']),
  makeCheatSheetItem('cs-cn-2', 'Computer Networks', 'Sliding Window Utilization', 'U=\\min\\left(1,\\frac{W}{1+2a}\\right), \\quad a=\\frac{T_p}{T_t}', 'tricky', ['data-link']),
  makeCheatSheetItem('cs-cn-3', 'Computer Networks', 'CRC Check', '\\text{append }r\\text{ zeros, divide by generator of degree }r, \\text{ append remainder}', 'frequent', ['error-control']),
  makeCheatSheetItem('cs-cn-4', 'Computer Networks', 'Hamming Distance', 'd_{min}\\ge d+1 \\text{ detects }d; \\quad d_{min}\\ge2t+1 \\text{ corrects }t', 'must-know', ['error-control']),
  makeCheatSheetItem('cs-cn-5', 'Computer Networks', 'IP Fragment Offset', '\\text{fragment offset is measured in 8-byte units}', 'frequent', ['ip']),

  makeCheatSheetItem('cs-ap-1', 'General Aptitude', 'Percentage Change', '\\%\\text{ change}=\\frac{\\text{new}-\\text{old}}{\\text{old}}\\times100', 'must-know', ['quant']),
  makeCheatSheetItem('cs-ap-2', 'General Aptitude', 'Successive Percentage Change', 'x\\% \\text{ then } y\\% \\Rightarrow x+y+\\frac{xy}{100}', 'frequent', ['quant']),
  makeCheatSheetItem('cs-ap-3', 'General Aptitude', 'Simple Interest', 'SI=\\frac{PRT}{100}', 'must-know', ['quant']),
  makeCheatSheetItem('cs-ap-4', 'General Aptitude', 'Compound Interest', 'A=P\\left(1+\\frac{r}{100}\\right)^t', 'must-know', ['quant']),
  makeCheatSheetItem('cs-ap-5', 'General Aptitude', 'Time And Work', '\\text{if A finishes in }x\\text{ days, rate}=1/x', 'frequent', ['quant']),
  makeCheatSheetItem('cs-ap-6', 'General Aptitude', 'Speed Distance Time', 'D=ST, \\quad \\text{average speed}=\\frac{\\text{total distance}}{\\text{total time}}', 'must-know', ['quant']),
  makeCheatSheetItem('cs-ap-7', 'General Aptitude', 'Permutation And Combination', '{}^nP_r=\\frac{n!}{(n-r)!}, \\quad {}^nC_r=\\frac{n!}{r!(n-r)!}', 'must-know', ['quant']),
];

// 180-minute exam day strategy
export const EXAM_DAY_STRATEGY = [
  { window: '0:00 - 0:10 (10 min)', activity: 'Read entire paper. Mark easy (E), medium (M), hard (H). Do not solve yet.', target: '—' },
  { window: '0:10 - 0:25 (15 min)', activity: 'Solve all 5 easy 1-mark aptitude questions. Then 5 easy 1-mark technical.', target: '~10 marks' },
  { window: '0:25 - 1:25 (60 min)', activity: 'Solve all easy + medium 1-mark and 2-mark technical questions. Skip any question taking >3 min.', target: '~30 marks' },
  { window: '1:25 - 1:40 (15 min)', activity: 'Break. Drink water. Stretch. Re-read skipped questions and reclassify.', target: '—' },
  { window: '1:40 - 2:40 (60 min)', activity: 'Attempt remaining medium + hard questions you can crack. Mind negative marking.', target: '~15 marks' },
  { window: '2:40 - 3:00 (20 min)', activity: 'Final pass: review all attempted for silly mistakes. Verify NAT answers.', target: 'Save 2-3 marks' },
];

// PYQ question distribution per subject per year (GATE CSE 2017–2026)
// Estimated from past paper patterns; 1-mark + 2-mark questions combined.
export const PYQ_DISTRIBUTION: Record<string, { year: number; count: number }[]> = {
  'eng-math': [
    { year: 2017, count: 8 }, { year: 2018, count: 9 }, { year: 2019, count: 8 },
    { year: 2020, count: 9 }, { year: 2021, count: 9 }, { year: 2022, count: 8 },
    { year: 2023, count: 9 }, { year: 2024, count: 8 }, { year: 2025, count: 9 }, { year: 2026, count: 9 },
  ],
  discrete: [
    { year: 2017, count: 5 }, { year: 2018, count: 5 }, { year: 2019, count: 5 },
    { year: 2020, count: 5 }, { year: 2021, count: 4 }, { year: 2022, count: 5 },
    { year: 2023, count: 5 }, { year: 2024, count: 4 }, { year: 2025, count: 5 }, { year: 2026, count: 5 },
  ],
  'digital-logic': [
    { year: 2017, count: 3 }, { year: 2018, count: 3 }, { year: 2019, count: 3 },
    { year: 2020, count: 3 }, { year: 2021, count: 3 }, { year: 2022, count: 3 },
    { year: 2023, count: 3 }, { year: 2024, count: 3 }, { year: 2025, count: 3 }, { year: 2026, count: 3 },
  ],
  coa: [
    { year: 2017, count: 5 }, { year: 2018, count: 5 }, { year: 2019, count: 5 },
    { year: 2020, count: 4 }, { year: 2021, count: 5 }, { year: 2022, count: 5 },
    { year: 2023, count: 4 }, { year: 2024, count: 5 }, { year: 2025, count: 5 }, { year: 2026, count: 5 },
  ],
  ds: [
    { year: 2017, count: 6 }, { year: 2018, count: 6 }, { year: 2019, count: 6 },
    { year: 2020, count: 6 }, { year: 2021, count: 6 }, { year: 2022, count: 6 },
    { year: 2023, count: 6 }, { year: 2024, count: 6 }, { year: 2025, count: 6 }, { year: 2026, count: 6 },
  ],
  algorithms: [
    { year: 2017, count: 7 }, { year: 2018, count: 7 }, { year: 2019, count: 7 },
    { year: 2020, count: 7 }, { year: 2021, count: 7 }, { year: 2022, count: 7 },
    { year: 2023, count: 7 }, { year: 2024, count: 7 }, { year: 2025, count: 7 }, { year: 2026, count: 7 },
  ],
  toc: [
    { year: 2017, count: 5 }, { year: 2018, count: 5 }, { year: 2019, count: 5 },
    { year: 2020, count: 5 }, { year: 2021, count: 5 }, { year: 2022, count: 5 },
    { year: 2023, count: 5 }, { year: 2024, count: 5 }, { year: 2025, count: 5 }, { year: 2026, count: 5 },
  ],
  compiler: [
    { year: 2017, count: 4 }, { year: 2018, count: 4 }, { year: 2019, count: 4 },
    { year: 2020, count: 4 }, { year: 2021, count: 3 }, { year: 2022, count: 4 },
    { year: 2023, count: 4 }, { year: 2024, count: 3 }, { year: 2025, count: 4 }, { year: 2026, count: 4 },
  ],
  os: [
    { year: 2017, count: 6 }, { year: 2018, count: 6 }, { year: 2019, count: 6 },
    { year: 2020, count: 6 }, { year: 2021, count: 6 }, { year: 2022, count: 6 },
    { year: 2023, count: 6 }, { year: 2024, count: 6 }, { year: 2025, count: 6 }, { year: 2026, count: 6 },
  ],
  dbms: [
    { year: 2017, count: 5 }, { year: 2018, count: 5 }, { year: 2019, count: 5 },
    { year: 2020, count: 5 }, { year: 2021, count: 5 }, { year: 2022, count: 5 },
    { year: 2023, count: 5 }, { year: 2024, count: 5 }, { year: 2025, count: 5 }, { year: 2026, count: 5 },
  ],
  networks: [
    { year: 2017, count: 5 }, { year: 2018, count: 5 }, { year: 2019, count: 5 },
    { year: 2020, count: 5 }, { year: 2021, count: 5 }, { year: 2022, count: 5 },
    { year: 2023, count: 5 }, { year: 2024, count: 5 }, { year: 2025, count: 5 }, { year: 2026, count: 5 },
  ],
  aptitude: [
    { year: 2017, count: 10 }, { year: 2018, count: 10 }, { year: 2019, count: 10 },
    { year: 2020, count: 10 }, { year: 2021, count: 10 }, { year: 2022, count: 10 },
    { year: 2023, count: 10 }, { year: 2024, count: 10 }, { year: 2025, count: 10 }, { year: 2026, count: 10 },
  ],
};

// Burnout warning signs
export const BURNOUT_SIGNS = [
  { sign: 'Sleep dropping below 7 hours for 3+ consecutive nights', severity: 'yellow', response: 'Mandatory 8-hour sleep for next 3 nights; cut 1 study block' },
  { sign: 'Mock scores dropping 5+ marks below recent average', severity: 'yellow', response: 'Take 2 days off mocks; revise strong subjects to rebuild confidence' },
  { sign: 'Loss of appetite or comfort eating', severity: 'orange', response: 'Reduce study hours by 30% for 1 week; consult counsellor if persists' },
  { sign: 'Inability to focus even on familiar topics', severity: 'orange', response: 'Take 1 full day off; do non-academic activity (walk, music, friends)' },
  { sign: 'Persistent negative thoughts about exam outcome', severity: 'red', response: 'Talk to family/friend; consider professional counselling; reduce intensity' },
  { sign: 'Physical symptoms (headache, GI issues, palpitations)', severity: 'red', response: 'Medical consultation immediately; full rest until symptoms clear' },
];
